### ISSUE TITLE
90_92_Fluclo_Shadowmoon (Alliance) - Quest option

### ISSUE THREAD

**Issue by Aldavor** [Ludovicus/WoW-Pro-Guides#420]
Looks like there's a number of issues regarding the quest "Building for Professions" (36100) given by Baros Alexston. I've just encountrered the situaton where I've already built profession buildings, and I no longer get this quest available, but WowPro still comes up with it. If we give these quest steps a |O| tag (and maybe add a note indicating it may not be available if buildings have already been completed), would that stop it reappearing on every reload if it's manually checked off the first time round?

**Comment by Ludovicus** [comment]
If you give them an |O| tag, they won't show up at all.  So that won't work.
I'll just add a |BUILDING|TownhallOnly| hander.  It will check for the townhall and no-buildings.

I just need to confirm that the townhall does not show up on the building list (99% certain).

**Comment by Ludovicus** [comment]
Yeah, only buildings placed on the planning table show up using C_Garrison.GetBuildings() .
So testing for an empty return should do the trick.

**Comment by Ludovicus** [comment]
OK  Checked in as 4d8215fb4e2521baac51b95e14d34ae2da8d91df

**Comment by Ludovicus** [comment]
PS:  I also have a bunch of toons parked in Shadowmoon racking up the Garrison resources and occasionally running missions and accumulating books.  Its funny how fast they can level just using the XP missions.   If I open up the mine the XP gains will be even higher.

**Comment by Aldavor** [comment]
I totally understand you... I have heirlooms that give me +45% experience which sends my levelling crazy, even in Draenor ;)

**Comment by Emmaleah** [comment]
Townhall only doesn't work as that would make it show up only if you have
zero buildings what you need to have is one empty small slot, which you
have after upgrading your town hall to level 2. <when you already may have
built 2 or 3 buildings >.
All that being said I don't know what actually causes this quest to show
up, it may h as ve multiple prerequisites or something, because it doesn't
always apprar when the guide says it should.

Last but not least,  I found a hack to get it to complete, if you have an
empty small plot (perhaps that you were saving for a salvage yard) you can
start the profession building, turn in the quest, then cancel the building
getting your gold and resources back.  The plot doesn't have to be empty,
but it will destroy anything in the plot so it's not wise if the plot isn't
empty.

**Comment by Ludovicus** [comment]
I think this is one of those edge cases where we may never have all the bases covered.
However, I think it is clear that if you have one of the profession buildings active, it will not show.
Even a level 1 garrison has a small plot you could put a profession building on.
So I will change TownhallOnly to something else to test that you have no profession buildings active.
That at least is a finite, but long set.
